In [1]:
from google.colab import files
uploaded = files.upload()

Saving petrol_consumption.csv to petrol_consumption.csv
Saving iris (1).csv to iris (1).csv
Saving drug.csv to drug.csv


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

iris = pd.read_csv("iris (1).csv")

X = iris.drop("species", axis=1)
y = iris["species"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("IRIS Accuracy:", accuracy_score(y_test, y_pred))
print("IRIS Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

IRIS Accuracy: 1.0
IRIS Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [5]:
from sklearn.preprocessing import LabelEncoder

drug = pd.read_csv("drug.csv")

le = LabelEncoder()
drug["Sex"] = le.fit_transform(drug["Sex"])
drug["BP"] = le.fit_transform(drug["BP"])
drug["Cholesterol"] = le.fit_transform(drug["Cholesterol"])
drug["Drug"] = le.fit_transform(drug["Drug"])

X = drug.drop("Drug", axis=1)
y = drug["Drug"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Drug Dataset Accuracy:", accuracy_score(y_test, y_pred))
print("Drug Dataset Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Drug Dataset Accuracy: 1.0
Drug Dataset Confusion Matrix:
[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [7]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

petrol = pd.read_csv("petrol_consumption.csv")

X = petrol.drop("Petrol_Consumption", axis=1)
y = petrol["Petrol_Consumption"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 91.5
Mean Squared Error: 17171.7
Root Mean Squared Error: 131.0408333306836
